### ISSUE TITLE
[BUG] Documentation for using Grafana Agent (Cloud)

### ISSUE THREAD

**Issue by sardaukar** [akoutmos/prom_ex#129]
**Describe the bug**
The docs have no examples on how to integrate with Grafana Cloud, even though https://github.com/akoutmos/prom_ex/pull/122  seems to indicate it's possible. A paragraph or so in the docs would be great.

**Comment by cigrainger** [comment]
I see this is closed, but were docs added?

**Comment by akoutmos** [comment]
Not sure why the issue was closed...but a tutorial for integrating with Grafana Cloud has not yet been written. It is on the todo list though :).

The docs should be enough to get you started though: https://hexdocs.pm/prom_ex/PromEx.Config.html 
Look for `:grafana_agent` and you'll see all the supported config settings.

**Comment by cigrainger** [comment]
Fantastic. Thanks so much @akoutmos!

**Comment by Mathitos** [comment]
any updates on this? I'm having trouble to integrate :/
