### ISSUE TITLE
Question: what is meant by datasource ID?

### ISSUE THREAD

**Issue by mikl** [akoutmos/prom_ex#30]
First of all, thanks for creating prom_ex.

Sorry if this is a really dumb question, but I was a bit confused by the instruction here:

> $ mix prom_ex.gen.config --datasource YOUR_PROMETHEUS_DATASOURCE_ID

I could not find any explanation of what you mean by `YOUR_PROMETHEUS_DATASOURCE_ID`. I presume it would be something like the application name? Maybe it corresponds to the service name in Prometheus?

Again, sorry if I’m being dumb here, but I figured I might not be the only one who might be confused.

**Comment by akoutmos** [comment]
Hey @mikl! Not a dumb question at all! As the library author I take for granted terminology that I use and issues like your help me make the documentation more thorough and explicit :).

The datasource ID is the ID of your Prometheus datasource in Grafana (see highlighted field in image below).

![image](https://user-images.githubusercontent.com/4753634/108546151-b7e84900-72b6-11eb-954e-f7cecba296ad.png)

Since PromEx can upload your Grafana dashboards for you, it needs to know what Grafana datasource to run the PromQL queries against.

If you are not using PromEx to upload your Grafana dashboards, you can provide any place holder you would like and it won't have any impact. On my todo list is to make that Mix task more interactive and walk you through setting it up and opt-in/out of various features. I'll leave this issue open for now until I update the docs :).

**Comment by mikl** [comment]
Ah, I didn’t think about Grafana. Thanks for explaining, and thanks again for making this.

**Comment by akoutmos** [comment]
Added a note in the readme on this. Thanks again!

**Comment by robsonpeixoto** [comment]
What do you think about instead of force a datasource id create a variable that allow the user choose the prometheus used for a specific dashboard? There are a lot a different approach to manage the observability infrastructure. For example:
You can have 1 prometheus for each environment but only one grafana access all prometheus. Or you can have a prometheus for each namespace for each kubernetes cluster.

A easy way to the developer do not care about it is add on the dashiboard a variable to choose the datasource(I don't know all required parameters, need to test it):
```json
  "templating": {
    "list": [
      {
        "hide": 0,
        "includeAll": false,
        "label": "prometheus",
        "multi": false,
        "name": "datasource",
        "options": [],
        "query": "prometheus",
        "queryValue": "",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "type": "datasource"
      }
    ]
  },
```

In all datasource you need to use id: `"datasource": "$datasource",`.

With this solution, do not matter the datasource name.

**Comment by akoutmos** [comment]
Hey @robsonpeixoto! At the moment, I don't think that this would become a feature directly. Although, this does raise a good question. I.e how can some simple massaging be done to the JSON Grafana templates after PromEx has gone through and done it's EEx pass?

Given that the dashboard definition is simply JSON, I could very easily see PromEx having a `transform` step, where you can provide an MFA and inject your own small snippets into the JSON dashboard definition. The you could set the datasource as you describe, and inject the additional template var. Thoughts?

**Comment by robsonpeixoto** [comment]
Yep, is possible @akoutmos.
