### ISSUE TITLE
[Question] How can we supply an alternative reporter? 

### ISSUE THREAD

**Issue by mrjoelkemp** [akoutmos/prom_ex#33]
Hey Alex,

We don't use prometheus, but have a custom metrics aggregator. I already have a reporter library that will connect to that aggregator and push metrics to it. I have two possible integration paths:

1. Reuse the PromEx plugs with our custom reporter. That way, we get the metrics emitting, get to use our own reporter, but also lose the dashboards.
2. Let PromEx do everything with the ability to supply a custom reporter.

I've read through the docs and have been looking through the code a bit to gather insights to these two integration paths. Would you happen to have some docs that explain either of these paths in more detail? Or do you have insights into which path you think would be best for our use case?

Thanks for the help and the library!

**Comment by akoutmos** [comment]
This is an interesting question, and something that I battled with when I started writing PromEx.

Currently there is no way to swap reporters. Prometheus is the only option supported by PromEx. The reason for this being that the dashboards that are included with PromEx and uploaded to Grafana are coupled to the metrics that are generated from the plugins. I craft each of the PromQL queries for each of the dashboard panels to fit the metrics that I collect in the plugins.

It would be possible to support say InfluxQL for each panel, but then the logic for rendering each dashboard grows significantly given that I would then need to write a PromQL query and an InfluxQL query for each panel and templatize them. If you then add any additional query languages that increases the level of effort. This route would be a lot of work, and would add a lot of complexity to the project unfortunately so I don't think I will go this route.

There are a couple of options here that I can think of though that may be of use to you. For one, a lot of other monitoring solution support reading from prometheus sources and inserting them into their own timeseries databases (one of the reasons why I adopted Prometheus specifically). For example, InfluxDB supports remote read&write from Prom DBs (https://www.influxdata.com/blog/influxdb-now-supports-prometheus-remote-read-write-natively/). So in theory you could have your metrics solution do something similar.

Another option would be for me to add something to PromEx to "export" all of the metrics definitions that I provide in an agnostic way so that you can do what you want with them outside of a PromEx context. The issues there would be that some of the plugins (for example the BEAM plugin) set up their own cron jobs to poll things like memory usage, atom counts, ets tables, etc. So something would need to execute those cron functions else those telemetry metrics handlers would never be triggered.

All this to say that there is nothing currently in PromEx to support what you are asking for (unfortunately). But it is an area that I am thinking about and hopefully will have some ideas down the road :).

If you want to hop on a Zoom call or something in the near future to dig deeper into this, I would be very interested!

**Comment by mrjoelkemp** [comment]
Thanks for the context, Alex. We're able to punt on this need in the short term, so in the future, I'll hack my way around to see how to reuse some of the plugins independently. The easiest/ideal path integration for us would be to reuse your plugins and bypass both prometheus and the grafana dashboard population. I understand that's violating some key design decisions.

Thanks again for the context and I hope we'll circle back again soon.

**Comment by akoutmos** [comment]
Sounds good! Sorry I couldn't have a better answer for you...but I will keep this in mind because it has come up a few times now.
