### ISSUE TITLE
[FEATURE] Datasource ID should be able to be configured inside config.ex/dev.ex/ etc.

### ISSUE THREAD

**Issue by saulbensach** [akoutmos/prom_ex#43]
**Is your feature request related to a problem? Please describe.**
I have a problem where we have different prometheus datasource names, so I need to be able to change the datasource_id in dashboard_assings depending on my env.
I can always create a new config env variable and write code inside `dashboard_assigns/0` call but it would be nice if prom_ex handles this.

**Describe the solution you would like to see**
It would be nice if we can have the following
```elixir
releases.exs

config :app_node, AppNode.PromEx,
  grafana: [
    host: System.fetch_env!("GRAFANA_URL"),
    auth_token: System.fetch_env!("GRAFANA_TOKEN")
  ],
  datasource_id: System.fetch_env!("PROMETHEUS_DATASOURCE")
```
Would know if datasource_id should be outside or inside grafana Keyword list.

**Comment by akoutmos** [comment]
Thanks for opening up the issue! The funny thing is that this is how I had this configured when PromEx was in Alpha. The reason that I decided to switch it to the way that it is now is that it is more explicit as to what is going on now (the datasource id is passed as an assign to the dashboard template). In addition, given that the `dashboard_assigns/0` function is is completely under your control, you can store this value in a config and read it yourself and pass it via the keyword list. Lastly, I want to keep the amount of application configuration to a minimum so that the library is easier to use and follows Elixir best practices (https://hexdocs.pm/elixir/master/library-guidelines.html#avoid-application-configuration).

Hopefully that all makes sense, and you can see where I am coming from on this one :). Let me know if you have any other questions, or feel free to close the issue.

**Comment by saulbensach** [comment]
Hey, makes total sense. Thanks for taking your time.
